begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values('44444444-4444-4444-8444-444444444444','call-a@example.test'),('55555555-5555-4555-8555-555555555555','call-b@example.test'),('66666666-6666-4666-8666-666666666666','call-o@example.test'),('77777777-7777-4777-8777-777777777777','call-m@example.test');
insert into public.profiles(id,role,name,handle) values('44444444-4444-4444-8444-444444444444','sponsor','A','call-a'),('55555555-5555-4555-8555-555555555555','sponsor','B','call-b'),('66666666-6666-4666-8666-666666666666','organizer','O','call-o'),('77777777-7777-4777-8777-777777777777','sponsor','M','call-m');
insert into public.organizations(id,slug,name,type,created_by) values('cccccccc-cccc-4ccc-8ccc-cccccccccccc','call-org','Sponsor Org','brand','44444444-4444-4444-8444-444444444444');
insert into public.organization_members(org_id,profile_id,role) values('cccccccc-cccc-4ccc-8ccc-cccccccccccc','66666666-6666-4666-8666-666666666666','admin'),('cccccccc-cccc-4ccc-8ccc-cccccccccccc','77777777-7777-4777-8777-777777777777','member');
set local role authenticated;
set local request.jwt.claims='{"sub":"44444444-4444-4444-8444-444444444444","role":"authenticated"}';
select lives_ok($$select public.create_call_opportunity('cccccccc-cccc-4ccc-8ccc-cccccccccccc','Sponsor developers','developers','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}','5k_25k')$$,'Sponsor admin creates Call and private budget');
select set_config('test.call_id',(select id::text from public.opportunities where owner_org_id='cccccccc-cccc-4ccc-8ccc-cccccccccccc' and slug='developers'),true);
select is((select type::text from public.opportunities where id=current_setting('test.call_id')::uuid),'call','shared call type');
select ok((select event_id is null from public.opportunities where id=current_setting('test.call_id')::uuid),'Call has no event');
select is((select created_by from public.opportunities where id=current_setting('test.call_id')::uuid),'44444444-4444-4444-8444-444444444444'::uuid,'derived creator');
select is((select status::text from public.opportunities where id=current_setting('test.call_id')::uuid),'draft','defaults draft');
select is((select count(*) from public.opportunity_call_details where opportunity_id=current_setting('test.call_id')::uuid),1::bigint,'exactly one details row');
select is((select budget_band from public.opportunity_call_budgets where opportunity_id=current_setting('test.call_id')::uuid),'5k_25k','owner reads distinctive budget');
select throws_ok($$update public.opportunities set type='package' where id=current_setting('test.call_id')::uuid$$,'42501',null,'type protected');
select throws_ok($$update public.opportunities set event_id=gen_random_uuid() where id=current_setting('test.call_id')::uuid$$,'42501',null,'event_id protected');
select throws_ok($$update public.opportunities set owner_org_id=gen_random_uuid() where id=current_setting('test.call_id')::uuid$$,'42501',null,'owner_org_id protected');
select throws_ok($$update public.opportunities set slug='changed' where id=current_setting('test.call_id')::uuid$$,'42501',null,'slug protected');
select throws_ok($$update public.opportunities set created_by='55555555-5555-4555-8555-555555555555' where id=current_setting('test.call_id')::uuid$$,'42501',null,'created_by protected');
select throws_ok($$insert into public.opportunities(type,owner_org_id,title,slug,created_by) values('call','cccccccc-cccc-4ccc-8ccc-cccccccccccc','Spoof','spoof','55555555-5555-4555-8555-555555555555')$$,'42501',null,'creator spoof denied');
select lives_ok($$update public.opportunity_call_budgets set budget_band='under_1k' where opportunity_id=current_setting('test.call_id')::uuid$$,'canonical under_1k accepted');
select lives_ok($$update public.opportunity_call_budgets set budget_band='1k_5k' where opportunity_id=current_setting('test.call_id')::uuid$$,'canonical 1k_5k accepted');
select lives_ok($$update public.opportunity_call_budgets set budget_band='5k_25k' where opportunity_id=current_setting('test.call_id')::uuid$$,'canonical 5k_25k accepted');
select lives_ok($$update public.opportunity_call_budgets set budget_band='25k_plus' where opportunity_id=current_setting('test.call_id')::uuid$$,'canonical 25k_plus accepted');
select throws_ok($$update public.opportunity_call_budgets set budget_band='random' where opportunity_id=current_setting('test.call_id')::uuid$$,'23514',null,'invalid band random rejected');
select throws_ok($$update public.opportunity_call_budgets set budget_band='100000' where opportunity_id=current_setting('test.call_id')::uuid$$,'23514',null,'invalid band 100000 rejected');
select throws_ok($$update public.opportunity_call_budgets set budget_band='usd_5k' where opportunity_id=current_setting('test.call_id')::uuid$$,'23514',null,'invalid band usd_5k rejected');
select throws_ok($$update public.opportunity_call_budgets set budget_band='' where opportunity_id=current_setting('test.call_id')::uuid$$,'23514',null,'invalid band empty rejected');
select throws_ok($$update public.opportunity_call_budgets set budget_band=null where opportunity_id=current_setting('test.call_id')::uuid$$,'23502',null,'NULL budget row rejected');
select throws_ok($$update public.opportunity_call_details set target_categories=array['invalid'] where opportunity_id=current_setting('test.call_id')::uuid$$,'23514',null,'target_categories taxonomy enforced');
select throws_ok($$update public.opportunity_call_details set target_regions=array['invalid'] where opportunity_id=current_setting('test.call_id')::uuid$$,'23514',null,'target_regions taxonomy enforced');
select throws_ok($$update public.opportunity_call_details set target_audience_types=array['invalid'] where opportunity_id=current_setting('test.call_id')::uuid$$,'23514',null,'target_audience_types taxonomy enforced');
select throws_ok($$update public.opportunity_call_details set target_attendance_bands=array['invalid'] where opportunity_id=current_setting('test.call_id')::uuid$$,'23514',null,'target_attendance_bands taxonomy enforced');
select throws_ok($$select public.create_call_opportunity('cccccccc-cccc-4ccc-8ccc-cccccccccccc','Rollback','rollback','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}','random')$$,'23514',null,'invalid budget creation rollback');
select is((select count(*) from public.opportunities where owner_org_id='cccccccc-cccc-4ccc-8ccc-cccccccccccc' and slug='rollback'),0::bigint,'no orphan');
select throws_ok($$select public.update_call_opportunity(current_setting('test.call_id')::uuid,'Changed','Changed','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}','random')$$,'23514',null,'invalid budget edit rollback');
select is((select title from public.opportunities where id=current_setting('test.call_id')::uuid),'Sponsor developers','public state rolled back');
select is((select budget_band from public.opportunity_call_budgets where opportunity_id=current_setting('test.call_id')::uuid),'25k_plus','private state rolled back');
select lives_ok($$select public.update_call_opportunity(current_setting('test.call_id')::uuid,'Sponsor developers','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}',null)$$,'clear private budget');
select is((select count(*) from public.opportunity_call_budgets where opportunity_id=current_setting('test.call_id')::uuid),0::bigint,'budget row removed');
select lives_ok($$update public.opportunities set status='published' where id=current_setting('test.call_id')::uuid$$,'publish without budget');
select lives_ok($$select public.update_call_opportunity(current_setting('test.call_id')::uuid,'Sponsor developers','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}','5k_25k')$$,'restore private budget');
set constraints all immediate;
set local request.jwt.claims='{"sub":"66666666-6666-4666-8666-666666666666","role":"authenticated"}';
select is((select count(*) from public.opportunities where id=current_setting('test.call_id')::uuid),1::bigint,'Organizer admin public Call visible');
select is((select count(*) from public.opportunity_call_budgets where opportunity_id=current_setting('test.call_id')::uuid),0::bigint,'Organizer admin budget hidden');
select throws_ok($$select public.create_call_opportunity('cccccccc-cccc-4ccc-8ccc-cccccccccccc','Denied','denied','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}',null)$$,'42501',null,'Organizer admin creation denied');
select throws_ok($$select public.update_call_opportunity(current_setting('test.call_id')::uuid,'Denied','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}',null)$$,'42501',null,'Organizer admin edit RPC denied');
with changed as(update public.opportunities set title='Denied' where id=current_setting('test.call_id')::uuid returning *) select is((select count(*) from changed),0::bigint,'Organizer admin opportunities update denied');
with changed as(update public.opportunity_call_details set target_regions=array['europe'] where opportunity_id=current_setting('test.call_id')::uuid returning *) select is((select count(*) from changed),0::bigint,'Organizer admin opportunity_call_details update denied');
with changed as(update public.opportunity_call_budgets set budget_band='under_1k' where opportunity_id=current_setting('test.call_id')::uuid returning *) select is((select count(*) from changed),0::bigint,'Organizer admin opportunity_call_budgets update denied');
set local request.jwt.claims='{"sub":"55555555-5555-4555-8555-555555555555","role":"authenticated"}';
select is((select count(*) from public.opportunities where id=current_setting('test.call_id')::uuid),1::bigint,'Unrelated Sponsor public Call visible');
select is((select count(*) from public.opportunity_call_budgets where opportunity_id=current_setting('test.call_id')::uuid),0::bigint,'Unrelated Sponsor budget hidden');
select throws_ok($$select public.create_call_opportunity('cccccccc-cccc-4ccc-8ccc-cccccccccccc','Denied','denied','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}',null)$$,'42501',null,'Unrelated Sponsor creation denied');
select throws_ok($$select public.update_call_opportunity(current_setting('test.call_id')::uuid,'Denied','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}',null)$$,'42501',null,'Unrelated Sponsor edit RPC denied');
with changed as(update public.opportunities set title='Denied' where id=current_setting('test.call_id')::uuid returning *) select is((select count(*) from changed),0::bigint,'Unrelated Sponsor opportunities update denied');
with changed as(update public.opportunity_call_details set target_regions=array['europe'] where opportunity_id=current_setting('test.call_id')::uuid returning *) select is((select count(*) from changed),0::bigint,'Unrelated Sponsor opportunity_call_details update denied');
with changed as(update public.opportunity_call_budgets set budget_band='under_1k' where opportunity_id=current_setting('test.call_id')::uuid returning *) select is((select count(*) from changed),0::bigint,'Unrelated Sponsor opportunity_call_budgets update denied');
set local request.jwt.claims='{"sub":"77777777-7777-4777-8777-777777777777","role":"authenticated"}';
select is((select count(*) from public.opportunities where id=current_setting('test.call_id')::uuid),1::bigint,'Sponsor member public Call visible');
select is((select count(*) from public.opportunity_call_budgets where opportunity_id=current_setting('test.call_id')::uuid),0::bigint,'Sponsor member budget hidden');
select throws_ok($$select public.create_call_opportunity('cccccccc-cccc-4ccc-8ccc-cccccccccccc','Denied','denied','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}',null)$$,'42501',null,'Sponsor member creation denied');
select throws_ok($$select public.update_call_opportunity(current_setting('test.call_id')::uuid,'Denied','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}',null)$$,'42501',null,'Sponsor member edit RPC denied');
with changed as(update public.opportunities set title='Denied' where id=current_setting('test.call_id')::uuid returning *) select is((select count(*) from changed),0::bigint,'Sponsor member opportunities update denied');
with changed as(update public.opportunity_call_details set target_regions=array['europe'] where opportunity_id=current_setting('test.call_id')::uuid returning *) select is((select count(*) from changed),0::bigint,'Sponsor member opportunity_call_details update denied');
with changed as(update public.opportunity_call_budgets set budget_band='under_1k' where opportunity_id=current_setting('test.call_id')::uuid returning *) select is((select count(*) from changed),0::bigint,'Sponsor member opportunity_call_budgets update denied');
set local role anon;
set local request.jwt.claims='{}';
select is((select count(*) from public.opportunities where id=current_setting('test.call_id')::uuid),1::bigint,'anonymous published Call visible');
select is((select count(*) from public.opportunity_call_details where opportunity_id=current_setting('test.call_id')::uuid),1::bigint,'anonymous published details visible');
select throws_ok($$select * from public.opportunity_call_budgets$$,'42501',null,'anonymous budget denied by grant');
select throws_ok($$select public.create_call_opportunity('cccccccc-cccc-4ccc-8ccc-cccccccccccc','Denied','denied','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}',null)$$,'42501',null,'anonymous RPC denied');
set local role authenticated;
set local request.jwt.claims='{"sub":"44444444-4444-4444-8444-444444444444","role":"authenticated"}';
update public.opportunities set status='draft' where id=current_setting('test.call_id')::uuid;
select is((select count(*) from public.opportunities where id=current_setting('test.call_id')::uuid),1::bigint,'owner draft visible');
set local role anon;
set local request.jwt.claims='{}';
select is((select count(*) from public.opportunities where id=current_setting('test.call_id')::uuid),0::bigint,'anonymous draft hidden');
select is((select count(*) from public.opportunity_call_details where opportunity_id=current_setting('test.call_id')::uuid),0::bigint,'anonymous draft details hidden');
set local role authenticated;
set local request.jwt.claims='{"sub":"55555555-5555-4555-8555-555555555555","role":"authenticated"}';
select is((select count(*) from public.opportunities where id=current_setting('test.call_id')::uuid),0::bigint,'unrelated draft hidden');
select is((select count(*) from public.opportunity_call_details where opportunity_id=current_setting('test.call_id')::uuid),0::bigint,'unrelated draft details hidden');
reset role;
grant update(owner_org_id) on public.opportunities to authenticated;
set local role authenticated;
set local request.jwt.claims='{"sub":"44444444-4444-4444-8444-444444444444","role":"authenticated"}';
select throws_ok($$update public.opportunities set owner_org_id=gen_random_uuid() where id=current_setting('test.call_id')::uuid$$,'23514',null,'owner immutable even with column grant');
select ok(not has_table_privilege('anon','public.opportunity_call_budgets','SELECT'),'no anonymous budget grants');
select ok((select not prosecdef from pg_proc where oid='public.create_call_opportunity(uuid,text,text,text,jsonb,text)'::regprocedure),'create SECURITY INVOKER');
select ok((select not prosecdef from pg_proc where oid='public.update_call_opportunity(uuid,text,text,jsonb,text)'::regprocedure),'edit SECURITY INVOKER');
select is((select count(*) from information_schema.columns where table_name in ('opportunities','opportunity_call_details') and column_name like '%budget%'),0::bigint,'no public budget columns');
reset role;
set constraints all deferred;
set local role authenticated;
set local request.jwt.claims='{"sub":"44444444-4444-4444-8444-444444444444","role":"authenticated"}';
update public.opportunities set status='published' where id=current_setting('test.call_id')::uuid;
set local request.jwt.claims='{"sub":"66666666-6666-4666-8666-666666666666","role":"authenticated"}';
select throws_ok($$insert into public.opportunity_call_budgets(opportunity_id,budget_band) values(current_setting('test.call_id')::uuid,'under_1k')$$,'23514',null,'Organizer budget INSERT denied');
with removed as(delete from public.opportunity_call_budgets where opportunity_id=current_setting('test.call_id')::uuid returning *) select is((select count(*) from removed),0::bigint,'Organizer budget DELETE denied');
select throws_ok($$insert into public.opportunities(type,owner_org_id,title,slug) values('call','cccccccc-cccc-4ccc-8ccc-cccccccccccc','Denied','direct-denied')$$,'42501',null,'Organizer direct Call INSERT denied');
set local request.jwt.claims='{"sub":"55555555-5555-4555-8555-555555555555","role":"authenticated"}';
select throws_ok($$insert into public.opportunity_call_budgets(opportunity_id,budget_band) values(current_setting('test.call_id')::uuid,'under_1k')$$,'23514',null,'Unrelated Sponsor budget INSERT denied');
with removed as(delete from public.opportunity_call_budgets where opportunity_id=current_setting('test.call_id')::uuid returning *) select is((select count(*) from removed),0::bigint,'Unrelated Sponsor budget DELETE denied');
select throws_ok($$insert into public.opportunities(type,owner_org_id,title,slug) values('call','cccccccc-cccc-4ccc-8ccc-cccccccccccc','Denied','direct-denied')$$,'42501',null,'Unrelated Sponsor direct Call INSERT denied');
set local request.jwt.claims='{"sub":"77777777-7777-4777-8777-777777777777","role":"authenticated"}';
select throws_ok($$insert into public.opportunity_call_budgets(opportunity_id,budget_band) values(current_setting('test.call_id')::uuid,'under_1k')$$,'23514',null,'Sponsor member budget INSERT denied');
with removed as(delete from public.opportunity_call_budgets where opportunity_id=current_setting('test.call_id')::uuid returning *) select is((select count(*) from removed),0::bigint,'Sponsor member budget DELETE denied');
select throws_ok($$insert into public.opportunities(type,owner_org_id,title,slug) values('call','cccccccc-cccc-4ccc-8ccc-cccccccccccc','Denied','direct-denied')$$,'42501',null,'Sponsor member direct Call INSERT denied');
set local request.jwt.claims='{"sub":"44444444-4444-4444-8444-444444444444","role":"authenticated"}';
select throws_ok($$select public.create_call_opportunity('cccccccc-cccc-4ccc-8ccc-cccccccccccc','Duplicate','developers','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}',null)$$,'23505',null,'same organization slug conflicts');
select throws_ok($$select public.create_call_opportunity('cccccccc-cccc-4ccc-8ccc-cccccccccccc','Bad criteria','bad-criteria','Text','{}',null)$$,'23514',null,'invalid details rollback');
select is((select count(*) from public.opportunities where slug='bad-criteria'),0::bigint,'invalid details leave no orphan');
reset role;
insert into public.organizations(id,slug,name,type,created_by) values('dddddddd-dddd-4ddd-8ddd-dddddddddddd','call-other','Other','brand','55555555-5555-4555-8555-555555555555');
set local role authenticated;
select throws_ok($$select public.create_call_opportunity('dddddddd-dddd-4ddd-8ddd-dddddddddddd','Wrong owner','wrong-owner','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}',null)$$,'42501',null,'owner organization spoof denied');
set local request.jwt.claims='{"sub":"55555555-5555-4555-8555-555555555555","role":"authenticated"}';
select lives_ok($$select public.create_call_opportunity('dddddddd-dddd-4ddd-8ddd-dddddddddddd','Other organization','developers','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}',null)$$,'same slug different organization allowed');
reset role;
select is((select count(*) from public.opportunities o join public.events e on e.id=o.event_id where o.type='package' and o.owner_org_id<>e.org_id),0::bigint,'package owner consistency');


reset role;
set constraints all deferred;
set local role authenticated;
set local request.jwt.claims='{"sub":"44444444-4444-4444-8444-444444444444","role":"authenticated"}';
select lives_ok($$select public.create_call_opportunity('cccccccc-cccc-4ccc-8ccc-cccccccccccc','Without budget','without-budget','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}',null)$$,'create with no budget');
select is((select count(*) from public.opportunity_call_budgets where opportunity_id=(select id from public.opportunities where owner_org_id='cccccccc-cccc-4ccc-8ccc-cccccccccccc' and slug='without-budget')),0::bigint,'no budget creates no row');
select lives_ok($$update public.opportunities set status='published' where owner_org_id='cccccccc-cccc-4ccc-8ccc-cccccccccccc' and slug='without-budget'$$,'new no-budget Call publishes');
select throws_ok($$select public.update_call_opportunity(current_setting('test.call_id')::uuid,'Bad edit','Text','{}','under_1k')$$,'23514',null,'invalid details edit rollback');
select is((select title from public.opportunities where id=current_setting('test.call_id')::uuid),'Sponsor developers','details failure retains title');
select is((select budget_band from public.opportunity_call_budgets where opportunity_id=current_setting('test.call_id')::uuid),'5k_25k','details failure retains band');
select is((select count(*) from public.opportunity_call_details where opportunity_id in(select id from public.opportunities where owner_org_id='cccccccc-cccc-4ccc-8ccc-cccccccccccc')),2::bigint,'failed creates leave no extra details');
select is((select count(*) from public.opportunity_call_budgets where opportunity_id in(select id from public.opportunities where owner_org_id='cccccccc-cccc-4ccc-8ccc-cccccccccccc')),1::bigint,'failed creates leave no extra budgets');
set local role anon;
select throws_ok($$select public.update_call_opportunity(current_setting('test.call_id')::uuid,'Denied','Text','{"target_categories":["hackathon"],"target_regions":["asia"],"target_audience_types":["developers"],"target_attendance_bands":["200-999"],"gives":["credits"]}',null)$$,'42501',null,'anonymous edit cannot execute');
reset role;
select is((select array_agg(column_name::text order by ordinal_position) from information_schema.columns where table_schema='public' and table_name='opportunity_call_budgets'),array['opportunity_id','budget_band','created_at','updated_at']::text[],'budget schema is band only');

select * from finish();rollback;
