begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values ('11111111-1111-4111-8111-111111111111','event-a@example.test'),('22222222-2222-4222-8222-222222222222','event-b@example.test'),('33333333-3333-4333-8333-333333333333','event-s@example.test');
insert into public.profiles(id,role,name,handle) values ('11111111-1111-4111-8111-111111111111','organizer','Organizer A','event-a'),('22222222-2222-4222-8222-222222222222','organizer','Organizer B','event-b'),('33333333-3333-4333-8333-333333333333','sponsor','Sponsor','event-s');
insert into public.organizations(slug,name,type,created_by) values ('org-a','Org A','event_company','11111111-1111-4111-8111-111111111111'),('org-b','Org B','event_company','22222222-2222-4222-8222-222222222222'),('org-s','Org S','brand','33333333-3333-4333-8333-333333333333');
insert into public.organization_members(org_id,profile_id,role) select id,'33333333-3333-4333-8333-333333333333','admin' from public.organizations where slug='org-a';
set local role authenticated;
set local request.jwt.claims='{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}';
select lives_ok($$insert into public.events(org_id,title,slug,format,starts_at,ends_at,timezone,categories,audience_types,attendance_band) values((select id from public.organizations where slug='org-a'),'Test event','event-a','online','2026-10-10 06:00Z','2026-10-10 08:00Z','Asia/Seoul',array['hackathon'],array['developers'],'200-999')$$,'Organizer admin creates draft');
select is((select status::text from public.events where slug='event-a'),'draft','creation defaults to draft');
select is((select created_by from public.events where slug='event-a'),'11111111-1111-4111-8111-111111111111'::uuid,'creator defaults to authenticated identity');
select throws_ok($$insert into public.events(org_id,title,slug,format,starts_at,ends_at,timezone,categories,audience_types,attendance_band) values((select id from public.organizations where slug='org-b'),'Test event','wrong-org','online','2026-10-10 06:00Z','2026-10-10 08:00Z','Asia/Seoul',array['hackathon'],array['developers'],'200-999')$$,'42501',null,'unrelated organization insert denied');
select throws_ok($$insert into public.events(org_id,title,slug,format,starts_at,ends_at,timezone,categories,audience_types,attendance_band) values(null,'Test event','null-org','online','2026-10-10 06:00Z','2026-10-10 08:00Z','Asia/Seoul',array['hackathon'],array['developers'],'200-999')$$,'42501',null,'org_id is required');
select throws_ok($$insert into public.events(org_id,title,slug,format,starts_at,ends_at,timezone,categories,audience_types,attendance_band,created_by) values((select id from public.organizations where slug='org-a'),'Test event','spoof-creator','online','2026-10-10 06:00Z','2026-10-10 08:00Z','Asia/Seoul',array['hackathon'],array['developers'],'200-999','22222222-2222-4222-8222-222222222222')$$,'42501',null,'creator spoof denied');
select throws_ok($$insert into public.events(org_id,title,slug,format,starts_at,ends_at,timezone,categories,audience_types,attendance_band,status) values((select id from public.organizations where slug='org-a'),'Test event','published-insert','online','2026-10-10 06:00Z','2026-10-10 08:00Z','Asia/Seoul',array['hackathon'],array['developers'],'200-999','published')$$,'42501',null,'cannot insert already published event');
select throws_ok($$insert into public.events(org_id,title,slug,format,starts_at,ends_at,timezone,categories,audience_types,attendance_band) values((select id from public.organizations where slug='org-a'),'Test event','event-a','online','2026-10-10 06:00Z','2026-10-10 08:00Z','Asia/Seoul',array['hackathon'],array['developers'],'200-999')$$,'23505',null,'duplicate slug rejected');
select lives_ok($$update public.events set title='Edited event' where slug='event-a'$$,'admin edits own event');
select is((select title from public.events where slug='event-a'),'Edited event','edit persisted');
select throws_ok($$update public.events set slug='changed-slug' where slug='event-a'$$,'42501',null,'protected slug update denied');
select throws_ok($$update public.events set org_id=(select id from public.organizations where slug='org-b') where slug='event-a'$$,'42501',null,'protected org_id update denied');
select throws_ok($$update public.events set created_by='22222222-2222-4222-8222-222222222222' where slug='event-a'$$,'42501',null,'protected created_by update denied');
select throws_ok($$update public.events set id=gen_random_uuid() where slug='event-a'$$,'42501',null,'protected id update denied');
select throws_ok($$update public.events set created_at=now() where slug='event-a'$$,'42501',null,'protected created_at update denied');
select throws_ok($$update public.events set updated_at=now() where slug='event-a'$$,'42501',null,'protected updated_at update denied');
select throws_ok($$update public.events set title='   ' where slug='event-a'$$,'23514',null,'reject invalid title: ''   ''');
select throws_ok($$update public.events set title=repeat('x',161) where slug='event-a'$$,'23514',null,'reject invalid title: repeat(''x'',161)');
select throws_ok($$update public.events set description=repeat('x',10001) where slug='event-a'$$,'23514',null,'reject invalid description: repeat(''x'',10001)');
select throws_ok($$update public.events set ends_at='2026-10-10 05:00Z' where slug='event-a'$$,'23514',null,'reject invalid ends_at: ''2026-10-10 05:00Z''');
select throws_ok($$update public.events set ends_at='2026-10-10 06:00Z' where slug='event-a'$$,'23514',null,'reject invalid ends_at: ''2026-10-10 06:00Z''');
select throws_ok($$update public.events set starts_at='-infinity' where slug='event-a'$$,'23514',null,'reject invalid starts_at: ''-infinity''');
select throws_ok($$update public.events set timezone='Not/A_Timezone' where slug='event-a'$$,'23514',null,'reject invalid timezone: ''Not/A_Timezone''');
select throws_ok($$update public.events set timezone='Mars/Olympus_Mons' where slug='event-a'$$,'23514',null,'reject invalid timezone: ''Mars/Olympus_Mons''');
select throws_ok($$update public.events set website='javascript:alert(1)' where slug='event-a'$$,'23514',null,'reject invalid website: ''javascript:alert(1)''');
select throws_ok($$update public.events set website='data:text/html,test' where slug='event-a'$$,'23514',null,'reject invalid website: ''data:text/html,test''');
select throws_ok($$update public.events set website='file:///tmp/a' where slug='event-a'$$,'23514',null,'reject invalid website: ''file:///tmp/a''');
select throws_ok($$update public.events set website='ftp://example.com' where slug='event-a'$$,'23514',null,'reject invalid website: ''ftp://example.com''');
select throws_ok($$update public.events set categories=array['unknown'] where slug='event-a'$$,'23514',null,'reject invalid categories: array[''unknown'']');
select throws_ok($$update public.events set categories=array[]::text[] where slug='event-a'$$,'23514',null,'reject invalid categories: array[]::text[]');
select throws_ok($$update public.events set categories=array[null]::text[] where slug='event-a'$$,'23514',null,'reject invalid categories: array[null]::text[]');
select throws_ok($$update public.events set audience_types=array['unknown'] where slug='event-a'$$,'23514',null,'reject invalid audience_types: array[''unknown'']');
select throws_ok($$update public.events set audience_types=array[]::text[] where slug='event-a'$$,'23514',null,'reject invalid audience_types: array[]::text[]');
select throws_ok($$update public.events set audience_types=array[null]::text[] where slug='event-a'$$,'23514',null,'reject invalid audience_types: array[null]::text[]');
select throws_ok($$update public.events set attendance_band='5000-plus' where slug='event-a'$$,'23514',null,'reject invalid attendance_band: ''5000-plus''');
select throws_ok($$update public.events set format='hybrid' where slug='event-a'$$,'23514',null,'reject invalid format: ''hybrid''');
select throws_ok($$update public.events set format='virtual' where slug='event-a'$$,'22P02',null,'format enum enforced');
select throws_ok($$update public.events set status='cancelled' where slug='event-a'$$,'22P02',null,'status enum enforced');
select lives_ok($$update public.events set timezone='America/New_York' where slug='event-a'$$,'New York timezone accepted');
select lives_ok($$update public.events set timezone='Asia/Seoul' where slug='event-a'$$,'Seoul timezone accepted');
select lives_ok($$update public.events set website='https://example.com' where slug='event-a'$$,'HTTPS accepted');
select lives_ok($$update public.events set website='http://example.com' where slug='event-a'$$,'HTTP accepted');
select lives_ok($$update public.events set format='in_person',city='Seoul',country='South Korea' where slug='event-a'$$,'physical event with location accepted');
select throws_ok($$delete from public.events where slug='event-a'$$,'42501',null,'client delete denied');
select ok(not has_table_privilege('authenticated','public.events','UPDATE'),'no broad UPDATE grant');
select ok(not has_table_privilege('authenticated','public.events','INSERT'),'no broad INSERT grant');
select ok(not has_function_privilege('authenticated','private.validate_event_timezone()','EXECUTE'),'timezone trigger is not callable');
select ok((select relrowsecurity from pg_class where oid='public.events'::regclass),'events RLS enabled');
set local request.jwt.claims='{"sub":"22222222-2222-4222-8222-222222222222","role":"authenticated"}';
select is((select count(*) from public.events where slug='event-a'),0::bigint,'unrelated Organizer cannot read draft');
select throws_ok($$insert into public.events(org_id,title,slug,format,starts_at,ends_at,timezone,categories,audience_types,attendance_band) values((select id from public.organizations where slug='org-a'),'Test event','denied-2','online','2026-10-10 06:00Z','2026-10-10 08:00Z','Asia/Seoul',array['hackathon'],array['developers'],'200-999')$$,'42501',null,'unrelated Organizer INSERT denied');
with changed as (update public.events set title='Unauthorized' where slug='event-a' returning id)
select is((select count(*) from changed),0::bigint,'unrelated Organizer UPDATE denied');
set local request.jwt.claims='{"sub":"33333333-3333-4333-8333-333333333333","role":"authenticated"}';
select is((select count(*) from public.events where slug='event-a'),0::bigint,'Sponsor admin cannot read draft');
select throws_ok($$insert into public.events(org_id,title,slug,format,starts_at,ends_at,timezone,categories,audience_types,attendance_band) values((select id from public.organizations where slug='org-s'),'Test event','denied-3','online','2026-10-10 06:00Z','2026-10-10 08:00Z','Asia/Seoul',array['hackathon'],array['developers'],'200-999')$$,'42501',null,'Sponsor admin INSERT denied');
with changed as (update public.events set title='Unauthorized' where slug='event-a' returning id)
select is((select count(*) from changed),0::bigint,'Sponsor admin UPDATE denied');
reset role;
set local role anon;
select is((select count(*) from public.events where slug='event-a'),0::bigint,'anonymous cannot read draft');
select throws_ok($$insert into public.events(org_id,title,slug,format,starts_at,ends_at,timezone,categories,audience_types,attendance_band) values((select id from public.organizations where slug='org-a'),'Test event','anon-event','online','2026-10-10 06:00Z','2026-10-10 08:00Z','Asia/Seoul',array['hackathon'],array['developers'],'200-999')$$,'42501',null,'anonymous INSERT denied');
reset role;
set local role authenticated;
set local request.jwt.claims='{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}';
select is((select count(*) from public.events where slug='event-a'),1::bigint,'owning Organizer admin sees draft');
select lives_ok($$update public.events set status='published' where slug='event-a'$$,'admin publishes');
reset role;
set local role anon;
select is((select count(*) from public.events where slug='event-a'),1::bigint,'anonymous sees published event');
reset role;
set local role authenticated;
set local request.jwt.claims='{"sub":"33333333-3333-4333-8333-333333333333","role":"authenticated"}';
with changed as (update public.events set title='Unauthorized' where slug='event-a' returning id)
select is((select count(*) from changed),0::bigint,'Sponsor cannot edit visible published event');
set local request.jwt.claims='{"sub":"22222222-2222-4222-8222-222222222222","role":"authenticated"}';
with changed as (update public.events set title='Unauthorized' where slug='event-a' returning id)
select is((select count(*) from changed),0::bigint,'unrelated Organizer cannot edit visible published event');
set local request.jwt.claims='{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}';
select lives_ok($$update public.events set status='draft' where slug='event-a'$$,'admin unpublishes');
reset role;
set local role anon;
select is((select count(*) from public.events where slug='event-a'),0::bigint,'unpublished event becomes private');
reset role;
-- Exercise immutable trigger independently of column grants.
grant update (slug,org_id,created_by) on public.events to authenticated;
set local role authenticated;
set local request.jwt.claims='{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}';
select throws_ok($$update public.events set slug='changed-slug' where slug='event-a'$$,'23514','Event identity cannot be changed after creation.','trigger protects slug independently');
select throws_ok($$update public.events set org_id=(select id from public.organizations where slug='org-b') where slug='event-a'$$,'23514','Event identity cannot be changed after creation.','trigger protects org_id independently');
select throws_ok($$update public.events set created_by='22222222-2222-4222-8222-222222222222' where slug='event-a'$$,'23514','Event identity cannot be changed after creation.','trigger protects created_by independently');
reset role;
insert into public.organization_members(org_id,profile_id,role)
  select id,'22222222-2222-4222-8222-222222222222','admin' from public.organizations where slug='org-a';
set local role authenticated;
set local request.jwt.claims='{"sub":"22222222-2222-4222-8222-222222222222","role":"authenticated"}';
select lives_ok($$update public.events set title='Managed by another org admin' where slug='event-a'$$,
  'another Organizer admin can manage event without being its creator');
select is((select created_by from public.events where slug='event-a'),
  '11111111-1111-4111-8111-111111111111'::uuid,'creator provenance remains unchanged');
select * from finish();
rollback;
