begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values ('11111111-1111-4111-8111-111111111111','opp-a@example.test'),('22222222-2222-4222-8222-222222222222','opp-b@example.test'),('33333333-3333-4333-8333-333333333333','opp-s@example.test');
insert into public.profiles(id,role,name,handle) values ('11111111-1111-4111-8111-111111111111','organizer','A','opp-a'),('22222222-2222-4222-8222-222222222222','organizer','B','opp-b'),('33333333-3333-4333-8333-333333333333','sponsor','S','opp-s');
insert into public.organizations(slug,name,type,created_by) values ('opp-org','Org','event_company','11111111-1111-4111-8111-111111111111');
insert into public.organization_members(org_id,profile_id,role) select id,'33333333-3333-4333-8333-333333333333','admin' from public.organizations where slug='opp-org';
insert into public.events(id,org_id,created_by,title,slug,format,starts_at,ends_at,timezone,categories,audience_types,attendance_band) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(select id from public.organizations where slug='opp-org'),'11111111-1111-4111-8111-111111111111','Event','opp-event','online','2026-10-10 06:00Z','2026-10-10 08:00Z','Asia/Seoul',array['hackathon'],array['developers'],'200-999');
set local role authenticated;
set local request.jwt.claims='{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}';
select lives_ok($$select public.create_package_opportunity('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Partner','partner','Text','[{"name":"Gold","price_minor":500000,"currency":"USD","in_kind":false,"benefits":["Logo"],"slots":2},{"name":"Cloud","price_minor":null,"currency":null,"in_kind":true,"benefits":["Credits"],"slots":null}]')$$,'owner creates cash and in-kind atomically');
select is((select count(*) from public.opportunity_tiers where opportunity_id=(select id from public.opportunities where slug='partner')),2::bigint,'two tiers');
select is((select created_by from public.opportunities where slug='partner'),'11111111-1111-4111-8111-111111111111'::uuid,'derived creator');
select is((select status::text from public.opportunities where slug='partner'),'draft','default draft');
select throws_ok($$update public.opportunities set type='call' where slug='partner'$$,'42501',null,'type immutable column grant');
select throws_ok($$update public.opportunities set event_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' where slug='partner'$$,'42501',null,'event_id immutable column grant');
select throws_ok($$update public.opportunities set slug='changed' where slug='partner'$$,'42501',null,'slug immutable column grant');
select throws_ok($$update public.opportunities set created_by='22222222-2222-4222-8222-222222222222' where slug='partner'$$,'42501',null,'created_by immutable column grant');
select throws_ok($$update public.opportunities set id=gen_random_uuid() where slug='partner'$$,'42501',null,'id immutable column grant');
select throws_ok($$update public.opportunities set created_at=now() where slug='partner'$$,'42501',null,'created_at immutable column grant');
select throws_ok($$insert into public.opportunities(event_id,title,slug,created_by) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Spoof','spoof','22222222-2222-4222-8222-222222222222')$$,'42501',null,'creator spoof');
select throws_ok($$insert into public.opportunities(type,title,slug) values('call','Call','call')$$,'42501',null,'call unavailable');
select throws_ok($$delete from public.opportunities where slug='partner'$$,'42501',null,'no opportunity delete');
select throws_ok($$update public.opportunity_tiers set price_minor=null where name='Gold'$$,'23514',null,'cash rejects price_minor null');
select throws_ok($$update public.opportunity_tiers set price_minor=0 where name='Gold'$$,'23514',null,'cash rejects price_minor 0');
select throws_ok($$update public.opportunity_tiers set price_minor=-1 where name='Gold'$$,'23514',null,'cash rejects price_minor -1');
select throws_ok($$update public.opportunity_tiers set currency=null where name='Gold'$$,'23514',null,'cash rejects currency null');
select throws_ok($$update public.opportunity_tiers set currency='usd' where name='Gold'$$,'23514',null,'cash rejects currency ''usd''');
select throws_ok($$update public.opportunity_tiers set currency='US' where name='Gold'$$,'23514',null,'cash rejects currency ''US''');
select throws_ok($$update public.opportunity_tiers set currency='USDD' where name='Gold'$$,'23514',null,'cash rejects currency ''USDD''');
select throws_ok($$update public.opportunity_tiers set currency='123' where name='Gold'$$,'23514',null,'cash rejects currency ''123''');
select throws_ok($$update public.opportunity_tiers set benefits=array[]::text[] where name='Gold'$$,'23514',null,'cash rejects benefits array[]::text[]');
select throws_ok($$update public.opportunity_tiers set benefits=array[' '] where name='Gold'$$,'23514',null,'cash rejects benefits array['' '']');
select throws_ok($$update public.opportunity_tiers set benefits=array[null]::text[] where name='Gold'$$,'23514',null,'cash rejects benefits array[null]::text[]');
select throws_ok($$update public.opportunity_tiers set slots=0 where name='Gold'$$,'23514',null,'cash rejects slots 0');
select throws_ok($$update public.opportunity_tiers set slots=-1 where name='Gold'$$,'23514',null,'cash rejects slots -1');
select throws_ok($$update public.opportunity_tiers set benefits=null where name='Gold'$$,'23502',null,'null benefits rejected');
select throws_ok($$update public.opportunity_tiers set price_minor=1000 where name='Cloud'$$,'23514',null,'in kind rejects price_minor');
select throws_ok($$update public.opportunity_tiers set currency='USD' where name='Cloud'$$,'23514',null,'in kind rejects currency');
select lives_ok($$update public.opportunity_tiers set currency='USD' where name='Gold'$$,'USD accepted');
select lives_ok($$update public.opportunity_tiers set currency='KRW' where name='Gold'$$,'KRW accepted');
select lives_ok($$update public.opportunity_tiers set currency='JPY' where name='Gold'$$,'JPY accepted');
update public.opportunity_tiers set currency='USD' where name='Gold';
select lives_ok($$update public.opportunity_tiers set slots=null where name='Gold'$$,'null slots accepted');
select lives_ok($$update public.opportunity_tiers set slots=5 where name='Gold'$$,'positive slots accepted');
select throws_ok($$select public.create_package_opportunity('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Rollback','rollback','Text','[{"name":"Bad","in_kind":false,"price_minor":0,"currency":"USD","benefits":["Logo"]}]')$$,'23514',null,'creation failure');
select is((select count(*) from public.opportunities where slug='rollback'),0::bigint,'no orphan after rollback');
select throws_ok($$select public.update_package_opportunity((select id from public.opportunities where slug='partner'),'Changed','Changed','[{"name":"Bad","in_kind":false,"price_minor":0,"currency":"USD","benefits":["Logo"]}]')$$,'23514',null,'edit failure');
select is((select title from public.opportunities where slug='partner'),'Partner','edit rollback retains title');
select is((select count(*) from public.opportunity_tiers where opportunity_id=(select id from public.opportunities where slug='partner')),2::bigint,'edit rollback retains tiers');
select lives_ok($$select public.update_package_opportunity((select id from public.opportunities where slug='partner'),'Partner edited','Text',(select jsonb_agg(jsonb_build_object('id',id,'name',name,'price_minor',price_minor,'currency',currency,'in_kind',in_kind,'benefits',benefits,'slots',slots)) from public.opportunity_tiers where opportunity_id=(select id from public.opportunities where slug='partner')))$$,'stable tier editing');
select is((select count(*) from public.opportunity_tiers where opportunity_id=(select id from public.opportunities where slug='partner')),2::bigint,'edit keeps tier count');
set constraints all immediate;
set local request.jwt.claims='{"sub":"33333333-3333-4333-8333-333333333333","role":"authenticated"}';
select is((select count(*) from public.opportunities where slug='partner'),0::bigint,'Sponsor draft hidden');
select throws_ok($$select public.create_package_opportunity('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Denied','denied','Text','[{"name":"Gold","price_minor":500000,"currency":"USD","in_kind":false,"benefits":["Logo"],"slots":2},{"name":"Cloud","price_minor":null,"currency":null,"in_kind":true,"benefits":["Credits"],"slots":null}]')$$,'42501',null,'Sponsor RPC denied');
select throws_ok($$insert into public.opportunities(event_id,title,slug) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Denied','denied')$$,'42501',null,'Sponsor insert denied');
with changed as(update public.opportunities set title='Unauthorized' where slug='partner' returning id) select is((select count(*) from changed),0::bigint,'Sponsor update denied');
with changed as(update public.opportunity_tiers set name='Unauthorized' returning id) select is((select count(*) from changed),0::bigint,'Sponsor tier update denied');
set local request.jwt.claims='{"sub":"22222222-2222-4222-8222-222222222222","role":"authenticated"}';
select is((select count(*) from public.opportunities where slug='partner'),0::bigint,'Unrelated Organizer draft hidden');
select throws_ok($$select public.create_package_opportunity('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Denied','denied','Text','[{"name":"Gold","price_minor":500000,"currency":"USD","in_kind":false,"benefits":["Logo"],"slots":2},{"name":"Cloud","price_minor":null,"currency":null,"in_kind":true,"benefits":["Credits"],"slots":null}]')$$,'42501',null,'Unrelated Organizer RPC denied');
select throws_ok($$insert into public.opportunities(event_id,title,slug) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Denied','denied')$$,'42501',null,'Unrelated Organizer insert denied');
with changed as(update public.opportunities set title='Unauthorized' where slug='partner' returning id) select is((select count(*) from changed),0::bigint,'Unrelated Organizer update denied');
with changed as(update public.opportunity_tiers set name='Unauthorized' returning id) select is((select count(*) from changed),0::bigint,'Unrelated Organizer tier update denied');
set local request.jwt.claims='{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}';
update public.events set status='draft' where id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
update public.opportunities set status='draft' where slug='partner';
select is((select count(*) from public.opportunities where slug='partner'),1::bigint,'owner sees draft/draft');
set local role anon;
set local request.jwt.claims='{}';
select is((select count(*) from public.opportunities where slug='partner'),0::bigint,'public visibility draft/draft');
select is((select count(*) from public.opportunity_tiers where opportunity_id=(select id from public.opportunities where slug='partner')),0::bigint,'tier visibility draft/draft');
set local role authenticated;
set local request.jwt.claims='{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}';
update public.events set status='draft' where id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
update public.opportunities set status='published' where slug='partner';
select is((select count(*) from public.opportunities where slug='partner'),1::bigint,'owner sees draft/published');
set local role anon;
set local request.jwt.claims='{}';
select is((select count(*) from public.opportunities where slug='partner'),0::bigint,'public visibility draft/published');
select is((select count(*) from public.opportunity_tiers where opportunity_id=(select id from public.opportunities where slug='partner')),0::bigint,'tier visibility draft/published');
set local role authenticated;
set local request.jwt.claims='{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}';
update public.events set status='published' where id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
update public.opportunities set status='draft' where slug='partner';
select is((select count(*) from public.opportunities where slug='partner'),1::bigint,'owner sees published/draft');
set local role anon;
set local request.jwt.claims='{}';
select is((select count(*) from public.opportunities where slug='partner'),0::bigint,'public visibility published/draft');
select is((select count(*) from public.opportunity_tiers where opportunity_id=(select id from public.opportunities where slug='partner')),0::bigint,'tier visibility published/draft');
set local role authenticated;
set local request.jwt.claims='{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}';
update public.events set status='published' where id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
update public.opportunities set status='published' where slug='partner';
select is((select count(*) from public.opportunities where slug='partner'),1::bigint,'owner sees published/published');
set local role anon;
set local request.jwt.claims='{}';
select is((select count(*) from public.opportunities where slug='partner'),1::bigint,'public visibility published/published');
select is((select count(*) from public.opportunity_tiers where opportunity_id=(select id from public.opportunities where slug='partner')),2::bigint,'tier visibility published/published');
set local role authenticated;
set local role anon;
select is((select price_minor from public.opportunity_tiers where name='Gold'),500000::bigint,'public cash price');
select is((select currency from public.opportunity_tiers where name='Gold'),'USD','public cash currency');
select ok((select price_minor is null and currency is null from public.opportunity_tiers where name='Cloud'),'public in-kind null cash');
set local role authenticated;
set local request.jwt.claims='{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}';
select throws_ok($$delete from public.opportunity_tiers$$,'23514',null,'cannot remove last published tier');
select is((select count(*) from public.opportunity_tiers where opportunity_id=(select id from public.opportunities where slug='partner')),2::bigint,'failed removal rolls back');
select ok(not has_table_privilege('authenticated','public.opportunities','UPDATE'),'no broad update');
select ok(not has_function_privilege('anon','public.create_package_opportunity(uuid,text,text,text,jsonb)','EXECUTE'),'anon cannot execute create');
select ok((select not prosecdef from pg_proc where oid='public.create_package_opportunity(uuid,text,text,text,jsonb)'::regprocedure),'create invoker');
select ok((select not prosecdef from pg_proc where oid='public.update_package_opportunity(uuid,text,text,jsonb)'::regprocedure),'edit invoker');
select is((select count(*) from information_schema.columns where table_name in ('opportunities','opportunity_tiers') and column_name like '%budget%'),0::bigint,'no public budget columns');
reset role;
set constraints all deferred;
insert into public.opportunities(type,owner_org_id,created_by,title,slug) values('call',(select id from public.organizations where slug='opp-org'),'33333333-3333-4333-8333-333333333333','Reserved','reserved');
insert into public.opportunity_call_details(opportunity_id,target_categories,target_regions,target_audience_types,target_attendance_bands)
select id,array['hackathon'],array['asia'],array['developers'],array['200-999'] from public.opportunities where slug='reserved';
set constraints all immediate;
select throws_ok($$insert into public.opportunity_tiers(opportunity_id,name,in_kind,benefits) values((select id from public.opportunities where slug='reserved'),'Invalid',true,array['Logo'])$$,'23514',null,'cannot attach tier to call');
reset role;
select set_config('test.opportunity_id',(select id::text from public.opportunities where slug='partner'),true);
set local role authenticated;

set local request.jwt.claims='{"sub":"33333333-3333-4333-8333-333333333333","role":"authenticated"}';
select throws_ok($$insert into public.opportunity_tiers(opportunity_id,name,in_kind,benefits) values(current_setting('test.opportunity_id')::uuid,'Denied',true,array['Logo'])$$,'23514',null,'Sponsor direct tier insert denied');
select throws_ok($$select public.update_package_opportunity(current_setting('test.opportunity_id')::uuid,'Denied','Text','[]')$$,'42501',null,'Sponsor edit RPC denied');
with changed as (delete from public.opportunity_tiers where opportunity_id=current_setting('test.opportunity_id')::uuid returning id) select is((select count(*) from changed),0::bigint,'Sponsor tier deletion denied');

set local request.jwt.claims='{"sub":"22222222-2222-4222-8222-222222222222","role":"authenticated"}';
select throws_ok($$insert into public.opportunity_tiers(opportunity_id,name,in_kind,benefits) values(current_setting('test.opportunity_id')::uuid,'Denied',true,array['Logo'])$$,'23514',null,'Unrelated Organizer direct tier insert denied');
select throws_ok($$select public.update_package_opportunity(current_setting('test.opportunity_id')::uuid,'Denied','Text','[]')$$,'42501',null,'Unrelated Organizer edit RPC denied');
with changed as (delete from public.opportunity_tiers where opportunity_id=current_setting('test.opportunity_id')::uuid returning id) select is((select count(*) from changed),0::bigint,'Unrelated Organizer tier deletion denied');
reset role;
grant update(type,event_id,slug,created_by,id,created_at) on public.opportunities to authenticated;
set local role authenticated;
set local request.jwt.claims='{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}';
select throws_ok($$update public.opportunities set type='call' where slug='partner'$$,'23514',null,'type independent trigger protection');
select throws_ok($$update public.opportunities set event_id=null where slug='partner'$$,'23514',null,'event_id independent trigger protection');
select throws_ok($$update public.opportunities set slug='changed' where slug='partner'$$,'23514',null,'slug independent trigger protection');
select throws_ok($$update public.opportunities set created_by='22222222-2222-4222-8222-222222222222' where slug='partner'$$,'23514',null,'created_by independent trigger protection');
select throws_ok($$update public.opportunities set id=gen_random_uuid() where slug='partner'$$,'23514',null,'id independent trigger protection');
select throws_ok($$update public.opportunities set created_at=now()+interval '1 day' where slug='partner'$$,'23514',null,'created_at independent trigger protection');
select throws_ok($$select public.create_package_opportunity('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Duplicate','partner','Text','[{"name":"Tier","in_kind":true,"benefits":["Logo"]}]')$$,'23505',null,'Event scoped duplicate rejected');
select throws_ok($$select public.update_package_opportunity(current_setting('test.opportunity_id')::uuid,'Changed','Text','[{"id":"eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee","name":"Tier","in_kind":true,"benefits":["Logo"]}]')$$,'42501',null,'foreign tier identity denied');
select is((select title from public.opportunities where slug='partner'),'Partner edited','foreign ID failure rolled back title');
reset role;
insert into public.events(id,org_id,created_by,title,slug,format,starts_at,ends_at,timezone,categories,audience_types,attendance_band)
select 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',org_id,created_by,title,'second-event',format,starts_at,ends_at,timezone,categories,audience_types,attendance_band from public.events where id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
set local role authenticated;
select lives_ok($$select public.create_package_opportunity('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','Other event','partner','Text','[{"name":"Tier","in_kind":true,"benefits":["Logo"]}]')$$,'same slug on different Event allowed');
reset role;

select * from finish(); rollback;
