begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values ('66666666-6666-4666-8666-666666666666','organization-test@example.test');
set local role authenticated;
set local request.jwt.claims='{"sub":"66666666-6666-4666-8666-666666666666","role":"authenticated"}';
insert into public.profiles(id,role,name,handle) values(auth.uid(),'organizer','Org Test','org-url-test');
select lives_ok($$insert into public.organizations(slug,name,type,domain,website,created_by) values('url-test','Test','event_company','example.com','https://example.com/path',auth.uid())$$,'authenticated creation accepts HTTPS');
select lives_ok($$insert into public.organizations(slug,name,type,domain,created_by) values('url-test-two','Test Two','brand','example.com',auth.uid())$$,'unverified organizations can share domain');
select is((select role::text from public.organization_members where org_id=(select id from public.organizations where slug='url-test')),'admin','creator gets admin atomically');
select lives_ok($$update public.organizations set website='http://example.com' where slug='url-test'$$,'HTTP accepted');
select throws_ok($$update public.organizations set website='javascript:alert(1)' where slug='url-test'$$,'23514',null,'javascript rejected by database');
select throws_ok($$update public.organizations set website='data:text/html,test' where slug='url-test'$$,'23514',null,'data rejected by database');
select throws_ok($$update public.organizations set website='file:///tmp/test' where slug='url-test'$$,'23514',null,'file rejected by database');
select throws_ok($$update public.organizations set website='ftp://example.com' where slug='url-test'$$,'23514',null,'FTP rejected');
select throws_ok($$update public.organizations set website='https://user:password@example.com' where slug='url-test'$$,'23514',null,'credentials rejected');
select lives_ok($$update public.organizations set website=null where slug='url-test'$$,'optional website accepts null');
select lives_ok($$update public.organizations set website='' where slug='url-test'$$,'optional website accepts empty');
select throws_ok($$update public.organizations set verified=true where slug='url-test'$$,'42501',null,'admin cannot self verify');
reset role;
set local role service_role;
select lives_ok($$update public.organizations set verified=true where slug='url-test'$$,'backend may verify');
reset role;
set local role authenticated;
select lives_ok($$update public.organizations set domain='other.example.com' where slug='url-test'$$,'admin changes domain');
select is((select verified from public.organizations where slug='url-test'),false,'domain change clears verification');
select * from finish();
rollback;
