import type {PropsWithChildren,ReactNode} from 'react';
import {ScrollView,Text,View} from 'react-native';
import {Link} from 'expo-router';
export const marketText='text-base leading-6 text-light-text dark:text-dark-text';
export const mutedText='text-sm leading-5 text-light-muted dark:text-dark-muted';
export function MarketplacePage({children}:PropsWithChildren){return <ScrollView className="flex-1 bg-light-background dark:bg-dark-background" keyboardShouldPersistTaps="handled" contentContainerStyle={{flexGrow:1}}><View className="w-full max-w-7xl self-center gap-lg px-md py-lg lg:px-xl lg:py-xl">{children}</View></ScrollView>;}
export function Badge({children}:PropsWithChildren){return <Text className="self-start rounded bg-light-background px-sm py-xs text-xs font-semibold tracking-wider text-light-muted dark:bg-dark-background dark:text-dark-muted">{children}</Text>;}
export function Chips({values}:{values:string[]}){return <View className="flex-row flex-wrap gap-sm">{values.filter(Boolean).map((value,i)=><Text key={value+i} className="rounded border border-light-border px-sm py-xs text-xs text-light-muted dark:border-dark-border dark:text-dark-muted">{value}</Text>)}</View>;}
export function Identity({name,subtitle}:{name:string;subtitle?:string}){return <View className="flex-row items-center gap-md"><View className="h-11 w-11 items-center justify-center rounded-lg bg-light-background dark:bg-dark-background"><Text className="text-base font-semibold text-light-text dark:text-dark-text">{name.trim().split(/\s+/).slice(0,2).map(x=>Array.from(x)[0]).join('').toUpperCase()}</Text></View><View className="min-w-0 flex-1 gap-xs"><Text className="text-sm font-semibold text-light-text dark:text-dark-text">{name}</Text>{subtitle?<Text className={mutedText}>{subtitle}</Text>:null}</View></View>;}
export function DetailLayout({title,badge,subtitle,children,sidebar}:{title:string;badge:string;subtitle:ReactNode;children:ReactNode;sidebar:ReactNode}){return <MarketplacePage><Link href="/explore" className={mutedText}>← Back to Explore</Link><View className="flex-col items-start gap-lg lg:flex-row"><View className="w-full min-w-0 flex-1 gap-lg"><View className="gap-md rounded-xl border border-light-border bg-light-surface p-lg dark:border-dark-border dark:bg-dark-surface lg:p-xl"><Badge>{badge}</Badge><Text accessibilityRole="header" className="text-3xl font-semibold leading-tight text-light-text dark:text-dark-text">{title}</Text>{subtitle}</View>{children}</View><View className="w-full gap-lg rounded-xl border border-light-border bg-light-surface p-lg dark:border-dark-border dark:bg-dark-surface lg:w-80">{sidebar}</View></View></MarketplacePage>;}
export function Section({title,children}:PropsWithChildren<{title:string}>){return <View className="gap-md rounded-xl border border-light-border bg-light-surface p-lg dark:border-dark-border dark:bg-dark-surface"><Text accessibilityRole="header" className="text-lg font-semibold text-light-text dark:text-dark-text">{title}</Text>{children}</View>;}
